### ISSUE TITLE
0.0.6 (RC4) Not working with macOS

### ISSUE THREAD

**Issue by passuf** [OokTech/TW5-SingleExecutable#1]
I just tried to run the latest release on macOS, but it crashes right after the start:

```
NodeSettings - No settings file, creating one with default values.
NodeSettings - Parsed raw settings.
Websockets listening on  8081
Serving on 127.0.0.1:8080
(press ctrl-C to exit)
$:/plugins/OokTech/MultiUser/ServerSide.js:29
  if ((wikiName.indexOf('/') === -1 && $tw.settings.wikis[wikiName]) || wikiName === 'RootWiki') {
                                                         ^

TypeError: Cannot read property 'RootWiki' of undefined
    at Object.ServerSide.loadWiki ($:/plugins/OokTech/MultiUser/ServerSide.js:29:58)
    at Object.handler ($:/plugins/OokTech/MultiUser/commands/wsserver.js:219:24)
    at SimpleServer.requestHandler ($:/plugins/OokTech/MultiUser/commands/wsserver.js:153:15)
    at Server.emit (events.js:159:13)
    at parserOnIncoming (_http_server.js:619:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
```

My environment:
```
node v10.0.0
macOS 10.13.4
```

I am just wondering, since version 0.0.5 (RC3) works for me.

Thanks for all your work and let me know if I can provide you with more details!

**Comment by inmysocks** [comment]
It looks like the problem is that the default settings file isn't being created before it is trying to read the settings.

As a quick fix if you go into the IndexWiki folder and create a folder called settings and inside that folder create a file called settings.json with this text:

```
{
"wikis": {}
}
```

than it should work. The fixed version should be up soon.

**Comment by passuf** [comment]
This resolved the issue, thank you very much!

**Comment by inmysocks** [comment]
I updated the executables so this shouldn't be needed anymore, but I have discovered another bug that in some cases prevents the settings from being saved on osx. Please let me know if you run into any other problems.

Thanks for the report!
