### ISSUE TITLE
Cannot get it to work on windows

### ISSUE THREAD

**Issue by gesundelehre** [OokTech/TW5-SingleExecutable#3]
Hello there,
in the readme.md it says "Download the executable for your system"
can you maybe tell me, how do i get the executable for windows?
Thank you in advance,
Simon

**Comment by passuf** [comment]
You can find the executable [here](https://github.com/OokTech/TW5-SingleExecutable/releases).

**Comment by inmysocks** [comment]
I will update the readme with a link to the releases.
